### ISSUE TITLE
ImportError: cannot import name 'parse' from 'ics'

### ISSUE THREAD

**Issue by SomeoneSerge** [simonw/datasette-ics#6]
https://github.com/simonw/datasette-ics/blob/c16091136c71da44025ee256a1f35fb493bee636/datasette_ics/__init__.py#L3

There does not appear to be any `parse` in `ics` version  `0.7` published on github: https://github.com/ics-py/ics-py/blob/v0.7/ics/__init__.py

I haven't checked if this could be an upstream versioning issue

**Comment by simonw** [comment]
Confirmed, that's a bug! Not sure how it got past my tests.

**Comment by SomeoneSerge** [comment]
https://github.com/simonw/datasette-ics/blob/f4c0520104cc404e19ae05c37da44463691529bd/setup.py#L35

Why was it necessary to pin the patch version?
Does the `v0.7` tag referenced above not conform to `datsette-ics`'s expectations?
